### PR TITLE
Added the option to share the current seed via the url hash

### PR DESCRIPTION
**Pull request by Delivator**

### CODE REVIEW

**Comment by Delivator** [comment]
Example: https://gfycat.com/PeriodicNeatAntelopegroundsquirrel

**Comment by Panda4994** [comment]
Hey, thanks for contributing! :-)
I really like this idea, just that I think we should just write the seed there (encoded for url that it won't break anything ofc) instead of using a hash.
I imagine people posting e.g. easteregg-seeds to each other with this feature and it's easier to keep track of the different links if you can just read them out of the URL rather than having to click it.
But I might be missing something. Do you see any advantage in a hash over the seed itself?

**Comment by Delivator** [comment]
Yeah I just used base64 encoding so that a valid url could be generated and I think encoded urls look kinda stupid sometimes :D. But urlencoding should work just fine!

**Comment by Delivator** [comment]
Updated in bd965d7efaf3b6f7cd96e0af27cf7dcfd6ab54cd
Screenshot

**Comment by Panda4994** [comment]
Oh, I just merged the previous pull request and made this change too :-)
I used encodeURIComponent, but I think both would work fine.

Anyway, thanks for the addition!
https://panda4994.github.io/seedinfo/seedinfo.html#-1821611317
(Check the Seeds as text ;-))

**Comment by Delivator** [comment]
https://panda4994.github.io/seedinfo/seedinfo.html#691399662 6th word :D

**Pull request merged**
